project:
  type: website

website:
  title: "rdocs"
  navbar:
    tools:
      - icon: github
      - href: https://github.com/daniellga/rdocs
        text: Github
  sidebar:
    style: "docked"
    contents:
      - section: "Functions"
        contents: ./functions.qmd 

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1000px