name: R-CMD-check

on:
  push:
    branches: [ main, master ]
    paths:
      - rdocs/**
  pull_request:
    branches: [ main, master ]
    paths:
      - rdocs/**
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # add this if

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ./rdocs
          extra-packages: any::rcmdcheck
          needs: check

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./rdocs
          args: 'c("--no-manual", "--no-build-vignettes", "--no-codoc", "--no-examples", "--no-tests")'
          error-on: '"error"'
